set(ZLIB_FOUND TRUE)
set(ZLIB_ROOT "/tmp/zlib-1.2.13")
set(ZLIB_LIBRARY "${ZLIB_ROOT}/zlib1.dll")
set(ZLIB_INCLUDE_DIR "${ZLIB_ROOT}")

if(ZLIB_FOUND AND NOT TARGET ZLIB::ZLIB)
  add_library(ZLIB::ZLIB SHARED IMPORTED)
  set_target_properties(ZLIB::ZLIB PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${ZLIB_LIBRARY}"
    IMPORTED_IMPLIB "${ZLIB_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES
      "${ZLIB_INCLUDE_DIR}"
    )
endif()

