set(OPENSSL_FOUND TRUE)
set(OpenSSL::SSL_FOUND TRUE)
set(OPENSSL_ROOT_DIR "/tmp/openssl-1.1.1t")
set(OPENSSL_LIBRARIES "${OPENSSL_ROOT_DIR}/apps")
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include")
set(OPENSSL_SSL_LIBRARY "${OPENSSL_LIBRARIES}/libssl-1_1-x64.dll")
set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_LIBRARIES}/libcrypto-1_1-x64.dll")
set(HAVE_OPENSSL_DES_H TRUE)
set(HAVE_OPENSSL_AES_H TRUE)
set(OPENSSL_VERSION "1.1.1t")

if(OPENSSL_FOUND AND NOT TARGET OpenSSL::SSL)
  add_library(OpenSSL::SSL SHARED IMPORTED)
  set_target_properties(OpenSSL::SSL PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
    IMPORTED_IMPLIB "${OPENSSL_SSL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    )

  target_include_directories(OpenSSL::SSL INTERFACE
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
    $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/utils/libssh/include>
    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/utils/libssh/include>
    )

endif()

if(OPENSSL_FOUND AND NOT TARGET OpenSSL::Crypto)
  add_library(OpenSSL::Crypto SHARED IMPORTED)
  set_target_properties(OpenSSL::Crypto PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
    IMPORTED_IMPLIB "${OPENSSL_CRYPTO_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    )
endif()
